### ISSUE TITLE
Funcionando..

### ISSUE THREAD

**Issue by Grooov3** [NyannRR/test2#1]
Opa, não vi onde está o problema que você disse, fiz o teste na extensão do pc (com o código original), apenas alterando o link do player pro seu link e funciona perfeitamente, tanto ep normal como premium.
Que erro dá pra você? é na extensão do pc ou a mobile?

**Comment by NyannRR** [comment]
No pc, caramba, então eu acho q o erro foi sempre no download q eu fiz, valeu cara kkkk

**Comment by NyannRR** [comment]
testei aqui, realmente é isso, caramba, q estranho kkkk

**Comment by NyannRR** [comment]
aliás, ele dava erro de legenda
