### ISSUE TITLE
Parceria

### ISSUE THREAD

**Issue by NedcloarBR** [NyannRR/test2#2]
Bom dia eu tenho umas ideias de coisas pra fazer no projeto e proponho uma parceria me add no Discord: NedcloarBR#0026

**Comment by NyannRR** [comment]
olha, eu até aceitaria, mas se vc quiser fazer parceria com alguém, fala com o criador real do projeto, no caso, eu só restaurei, pq ele removeu o repositório, pro povo poder continuar usando, e eu também não sei muito bem programar, o criador é o itallolegal (no github)

**Comment by NedcloarBR** [comment]
Então a conta dele foi deletada e foi criada uma nova hoje de manha mas não tem como saber se essa conta é dele mesmo e tmb acho que ele deletou o projeto pois a Crunchyroll foi comprada recentemente e acho que ele deletou pra evitar problemas. Também não sei programar muito estou aprendendo ainda.

**Comment by NyannRR** [comment]
Se você quiser pode usar um fork, e mudar os arquivos livremente como vc puder

**Comment by NedcloarBR** [comment]
Eu já tinha o projeto todo baixado antes de cair o repo original eu propus a parceria pra nós criarmos ideias e por elas em prática em ambos os repositórios
Ontem quando postei meu repositório já integrei um dark mode automático pra página e estou fazendo um botão que ativa e desativa o script e em breve farei uma integração com DiscordRPC(RichPresence)
